### ISSUE TITLE
When running I get exception in a popup

### ISSUE THREAD

**Issue by lustefaniak** [antoniogarrote/mondello#1]
```
Uncaught Exception:
Error
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:15831:14)
    at $c_sjsr_UndefinedBehaviorError.fillInStackTrace__jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:31082:67)
    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.init___T__jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:15934:8)
    at $c_sjsr_UndefinedBehaviorError.init___T__jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:31092:52)
    at $c_sjsr_UndefinedBehaviorError.init___jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:31088:67)
    at $throwClassCastException (/Applications/Mondello.app/Contents/Resources/app/main.js:212:46)
    at $as_jl_Throwable (/Applications/Mondello.app/Contents/Resources/app/main.js:15941:61)
    at ReadFileContext.callback (/Applications/Mondello.app/Contents/Resources/app/main.js:1176:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```

I use Docker Beta for Mac

**Comment by antoniogarrote** [comment]
Hi thanks for testing the app. 

Which version are you trying?

I think version 0.2.3 should have fixed that problem.

**Comment by lustefaniak** [comment]
I tried 0.2.1 and it failed, version 0.2.3 starts properly. Thanks!
